CREATE TABLE [dbo].[Product]
(
    [ProductId] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_Product] PRIMARY KEY,
    [Sku] NVARCHAR(50) NOT NULL CONSTRAINT [UQ_Product_Sku] UNIQUE,
    [Name] NVARCHAR(200) NOT NULL,
    [Price] DECIMAL(18,2) NOT NULL,
    [CreatedUtc] DATETIME2 NOT NULL CONSTRAINT [DF_Product_CreatedUtc] DEFAULT (SYSUTCDATETIME())
);
