CREATE TABLE [dbo].[Sample]
(
    [Id] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_Sample] PRIMARY KEY,
    [Name] NVARCHAR(200) NOT NULL,
    [CreatedUtc] DATETIME2 NOT NULL CONSTRAINT [DF_Sample_CreatedUtc] DEFAULT (SYSUTCDATETIME())
);
